XDG_BIN_HOME=${XDG_BIN_HOME:-$HOME/.local/bin}
XDG_CACHE_HOME=${XDG_CACHE_HOME:-$HOME/.cache}
XDG_CONFIG_HOME=${XDG_CONFIG_HOME:-$HOME/.config}
XDG_DATA_HOME=${XDG_DATA_HOME:-$HOME/.local/share}
XDG_STATE_HOME=${XDG_STATE_HOME:-$HOME/.local/state}
XDG_RUNTIME_DIR=${XDG_RUNTIME_DIR:-/run/user/$(id -u)}

BACKUP_DIR=${BACKUP_DIR:-$HOME/.sodot/backup}

ZDOT_DIR=${ZDOT_DIR:-$XDG_CONFIG_HOME/zsh}

EDITOR=nvim
VISUAL=nvim

SD_PLUGIN_DIR=${SD_PLUGIN_DIR:-$XDG_DATA_HOME/sodot/plugins}
SD_SSH_HOME=${SD_SSH_HOME:-$HOME/.ssh}
